#ifndef OMNI3WDBOT_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_
#define OMNI3WDBOT_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define OMNI3WDBOT_HARDWARE_INTERFACE_EXPORT __attribute__((dllexport))
#define OMNI3WDBOT_HARDWARE_INTERFACE_IMPORT __attribute__((dllimport))
#else
#define OMNI3WDBOT_HARDWARE_INTERFACE_EXPORT __declspec(dllexport)
#define OMNI3WDBOT_HARDWARE_INTERFACE_IMPORT __declspec(dllimport)
#endif
#ifdef OMNI3WDBOT_HARDWARE_INTERFACE_BUILDING_DLL
#define OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC OMNI3WDBOT_HARDWARE_INTERFACE_EXPORT
#else
#define OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC OMNI3WDBOT_HARDWARE_INTERFACE_IMPORT
#endif
#define OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC_TYPE OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC
#define OMNI3WDBOT_HARDWARE_INTERFACE_LOCAL
#else
#define OMNI3WDBOT_HARDWARE_INTERFACE_EXPORT __attribute__((visibility("default")))
#define OMNI3WDBOT_HARDWARE_INTERFACE_IMPORT
#if __GNUC__ >= 4
#define OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC __attribute__((visibility("default")))
#define OMNI3WDBOT_HARDWARE_INTERFACE_LOCAL __attribute__((visibility("hidden")))
#else
#define OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC
#define OMNI3WDBOT_HARDWARE_INTERFACE_LOCAL
#endif
#define OMNI3WDBOT_HARDWARE_INTERFACE_PUBLIC_TYPE
#endif

#endif //OMNI3WDBOT_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_